# app/config/application.yml
defaults: &defaults
  site_name: toulouse.rb
  ganalytics: UA-15304320-1
  logs:
    email: email.log
    scm: scm.log

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults